# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'label.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1185, 741)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../.designer/backup/resource/logo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("font: 75 10pt \"Consolas\";")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.IdText = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.IdText.setGeometry(QtCore.QRect(410, 100, 241, 41))
        self.IdText.setObjectName("IdText")
        self.MethodButton = QtWidgets.QPushButton(self.centralwidget)
        self.MethodButton.setGeometry(QtCore.QRect(500, 450, 111, 61))
        self.MethodButton.setStyleSheet("background-color:rgb(255, 170, 0)")
        self.MethodButton.setObjectName("MethodButton")
        self.ProblemButton = QtWidgets.QPushButton(self.centralwidget)
        self.ProblemButton.setGeometry(QtCore.QRect(360, 450, 111, 61))
        self.ProblemButton.setStyleSheet("background-color:rgb(0, 170, 255)")
        self.ProblemButton.setObjectName("ProblemButton")
        self.SentenceText = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.SentenceText.setGeometry(QtCore.QRect(180, 160, 741, 261))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.SentenceText.setFont(font)
        self.SentenceText.setStyleSheet("background-color:rgb(194, 255, 184)")
        self.SentenceText.setObjectName("SentenceText")
        self.OtherButton = QtWidgets.QPushButton(self.centralwidget)
        self.OtherButton.setGeometry(QtCore.QRect(790, 450, 101, 61))
        self.OtherButton.setStyleSheet("background-color:rgb(0, 255, 255)")
        self.OtherButton.setObjectName("OtherButton")
        self.BackgroundButton = QtWidgets.QPushButton(self.centralwidget)
        self.BackgroundButton.setGeometry(QtCore.QRect(210, 450, 111, 61))
        self.BackgroundButton.setStyleSheet("background-color:rgb(0, 170, 0)\n"
"")
        self.BackgroundButton.setObjectName("BackgroundButton")
        self.ResultButton = QtWidgets.QPushButton(self.centralwidget)
        self.ResultButton.setGeometry(QtCore.QRect(640, 450, 121, 61))
        self.ResultButton.setStyleSheet("background-color:rgb(255, 85, 0)")
        self.ResultButton.setObjectName("ResultButton")
        self.PathText = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.PathText.setGeometry(QtCore.QRect(180, 100, 201, 41))
        self.PathText.setObjectName("PathText")
        self.DoneText = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.DoneText.setGeometry(QtCore.QRect(670, 100, 251, 41))
        self.DoneText.setObjectName("DoneText")
        self.NextButton = QtWidgets.QPushButton(self.centralwidget)
        self.NextButton.setGeometry(QtCore.QRect(500, 560, 111, 61))
        self.NextButton.setStyleSheet("background-color:rgb(199, 134, 255)")
        self.NextButton.setObjectName("NextButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1185, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionRollBack = QtWidgets.QAction(MainWindow)
        self.actionRollBack.setObjectName("actionRollBack")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionRollBack)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Academic paper abstract sentence label tool"))
        self.MethodButton.setText(_translate("MainWindow", "Method"))
        self.ProblemButton.setText(_translate("MainWindow", "Problem"))
        self.OtherButton.setText(_translate("MainWindow", "Other"))
        self.BackgroundButton.setText(_translate("MainWindow", "Background"))
        self.ResultButton.setText(_translate("MainWindow", "Result"))
        self.NextButton.setText(_translate("MainWindow", "Next"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionRollBack.setText(_translate("MainWindow", "RollBack"))
        self.actionRollBack.setShortcut(_translate("MainWindow", "Ctrl+`"))

